name: pip test

on:
  push:
    branches: [ main, 'v[0-9]+.x' ]
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    # nanobind requires macOS >= 10.14
    # std::filesystem requires macOS >= 10.15
    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV

    - name: Build and install
      run: pip install --verbose .

    - name: Test
      run: python -m unittest discover -s tests
